country: honduras
election_date: '2025-11-30'
start_date: '2025-11-12'
end_date: '2025-12-05'

candidates:
  - candidate_id: hnd01monc
    name: Rixi Ramona Moncada
    name_variations:
      - Rixi Moncada
      - Rixi Ramona
      - Rixi
      - Rixi Ramona Moncada
    keywords:
      - Rixi Ramona Moncada
    youtube_profile_url: https://www.youtube.com/@rixipresidenta
    instagram_profile_url: https://www.instagram.com/rixipresidenta/
    twitter_profile_url: https://x.com/RixiPresidenta
    twitter_username: RixiPresidenta
    instagram_username: rixipresidenta
    youtube_username: '@rixipresidenta'
    youtube_channel_id: UCDe9xhIjHpxmGZjt1HUrcTg
    youtube_uploads_playlist_id: UUDe9xhIjHpxmGZjt1HUrcTg

  - candidate_id: hnd02cast
    name: Xiomara Castro de Zelaya
    name_variations:
      - Xiomara Castro
      - Xiomara
    keywords:
      - Xiomara Castro de Zelaya
    youtube_profile_url: https://www.youtube.com/@xiomaracastroz
    instagram_profile_url: https://www.instagram.com/xiomaracastroz/
    twitter_profile_url: https://x.com/XiomaraCastroZ
    twitter_username: XiomaraCastroZ
    instagram_username: xiomaracastroz
    youtube_username: '@xiomaracastroz'
    youtube_channel_id: UC8_NyEjsT6mVAf7TRIR93NQ
    youtube_uploads_playlist_id: UU8_NyEjsT6mVAf7TRIR93NQ

  - candidate_id: hnd03gonz
    name: Yamileth Gonzales
    name_variations:
      - Yamileth Gonzales
      - Yamileth Gonzalez
    keywords:
      - Yamileth Gonzales
    youtube_profile_url: null
    instagram_profile_url: https://www.instagram.com/yamilethgonzaleshn/
    twitter_profile_url: https://x.com/YamiGonzalesj
    twitter_username: YamiGonzalesj
    instagram_username: yamilethgonzaleshn
    youtube_username: null
    youtube_channel_id: null
    youtube_uploads_playlist_id: null

  - candidate_id: hnd04guan
    name: Karen Guandique
    name_variations:
      - Karen Guandique
    keywords:
      - Karen Guandique
    youtube_profile_url: null
    instagram_profile_url: https://www.instagram.com/karenguandique7/
    twitter_profile_url: https://x.com/KarenGuandique
    twitter_username: KarenGuandique
    instagram_username: karenguandique7
    youtube_username: null
    youtube_channel_id: null
    youtube_uploads_playlist_id: null

  - candidate_id: hnd05pere
    name: Kritza Pérez
    name_variations:
      - Kritza Pérez
    keywords:
      - Kritza Pérez
    youtube_profile_url: null
    instagram_profile_url: https://www.instagram.com/kritzaperez/
    twitter_profile_url: https://x.com/KritzaPerez
    twitter_username: KritzaPerez
    instagram_username: kritzaperez
    youtube_username: null
    youtube_channel_id: null
    youtube_uploads_playlist_id: null

  - candidate_id: hnd06hayd
    name: Carmen Haydeé
    name_variations:
      - Carmen Haydeé
    keywords:
      - Carmen Haydeé
    youtube_profile_url: null
    instagram_profile_url: https://www.instagram.com/haydeevos/?hl=es
    twitter_profile_url: https://x.com/flophaydee?lang=es
    twitter_username: flophaydee
    instagram_username: haydeevos
    youtube_username: null
    youtube_channel_id: null
    youtube_uploads_playlist_id: null

  - candidate_id: hnd07elvi
    name: Iroshka Elvir
    name_variations:
      - Iroshka Elvir
    keywords:
      - Iroshka Elvir
    youtube_profile_url: null
    instagram_profile_url: https://www.instagram.com/iroshka_nasralla/?hl=es
    twitter_profile_url: https://x.com/IroshkaElvir
    twitter_username: IroshkaElvir
    instagram_username: iroshka_nasralla
    youtube_username: null
    youtube_channel_id: null
    youtube_uploads_playlist_id: null

  - candidate_id: hnd08cano
    name: Lissi Matute Cano
    name_variations:
      - Lissi Matute Cano
    keywords:
      - Lissi Matute Cano
    youtube_profile_url: null
    instagram_profile_url: https://www.instagram.com/lissimatutecano/
    twitter_profile_url: https://x.com/LissiCano
    twitter_username: LissiCano
    instagram_username: lissimatutecano
    youtube_username: null
    youtube_channel_id: null
    youtube_uploads_playlist_id: null

  - candidate_id: hnd09sosa
    name: Maria José Sosa
    name_variations:
      - Maria José Sosa
    keywords:
      - Maria José Sosa
    youtube_profile_url: null
    instagram_profile_url: https://www.instagram.com/soymj17/?hl=es-la
    twitter_profile_url: https://x.com/soymj17
    twitter_username: soymj17
    instagram_username: soymj17
    youtube_username: null
    youtube_channel_id: null
    youtube_uploads_playlist_id: null

  - candidate_id: hnd10sier
    name: Grace Sierra
    name_variations:
      - Grace Sierra
    keywords:
      - Grace Sierra
    youtube_profile_url: null
    instagram_profile_url: https://www.instagram.com/gracesierrahn/
    twitter_profile_url: https://x.com/GraceSierra1
    twitter_username: GraceSierra1
    instagram_username: gracesierrahn
    youtube_username: null
    youtube_channel_id: null
    youtube_uploads_playlist_id: null

  - candidate_id: hnd11pine
    name: Iris Pineda
    name_variations:
      - Iris Pineda
    keywords:
      - Iris Pineda
    youtube_profile_url: null
    instagram_profile_url: https://www.instagram.com/diputadairispineda/
    twitter_profile_url: https://x.com/IrisPinedaPaz
    twitter_username: IrisPinedaPaz
    instagram_username: diputadairispineda
    youtube_username: null
    youtube_channel_id: null
    youtube_uploads_playlist_id: null

  - candidate_id: hnd12ando
    name: Daisy Andonie
    name_variations:
      - Daisy Andonie
    keywords:
      - Daisy Andonie
    youtube_profile_url: null
    instagram_profile_url: https://www.instagram.com/daisyandoniel/
    twitter_profile_url: https://x.com/DaisyAndonie
    twitter_username: DaisyAndonie
    instagram_username: daisyandoniel
    youtube_username: null
    youtube_channel_id: null
    youtube_uploads_playlist_id: null

  - candidate_id: hnd13hall
    name: Ana Paola Hall
    name_variations:
      - Ana Paola Hall
    keywords:
      - Ana Paola Hall
    youtube_profile_url: null
    instagram_profile_url: https://www.instagram.com/anap.hall/?hl=en
    twitter_profile_url: https://x.com/APHall_CNE
    twitter_username: APHall_CNE
    instagram_username: anap.hall
    youtube_username: null
    youtube_channel_id: null
    youtube_uploads_playlist_id: null

  - candidate_id: hnd14espi
    name: Maribel Espinoza
    name_variations:
      - Maribel Espinoza
    keywords:
      - Maribel Espinoza
    youtube_profile_url: null
    instagram_profile_url: https://www.instagram.com/mespinoza.hn/?hl=es
    twitter_profile_url: https://x.com/MaribelE59
    twitter_username: MaribelE59
    instagram_username: mespinoza.hn
    youtube_username: null
    youtube_channel_id: null
    youtube_uploads_playlist_id: null

  - candidate_id: hnd15lope
    name: Cossette López
    name_variations:
      - Cossette López
    keywords:
      - Cossette López
    youtube_profile_url: null
    instagram_profile_url: https://www.instagram.com/cossetteoficial/
    twitter_profile_url: https://x.com/CossetteOficial
    twitter_username: CossetteOficial
    instagram_username: cossetteoficial
    youtube_username: null
    youtube_channel_id: null
    youtube_uploads_playlist_id: null

  - candidate_id: hnd16asfu
    name: Nasry Asfura
    name_variations:
      - Nasry Asfura
      - Tito Asfura
    keywords:
      - Nasry Asfura
    youtube_profile_url: https://www.youtube.com/c/NasryTitoAsfura
    instagram_profile_url: https://www.instagram.com/papialaorden/
    twitter_profile_url: https://x.com/titoasfura?lang=es
    twitter_username: titoasfura
    instagram_username: papialaorden
    youtube_username: NasryTitoAsfura
    youtube_channel_id: UCIZviNZ2baLody7GJagxgLA
    youtube_uploads_playlist_id: UUIZviNZ2baLody7GJagxgLA

  - candidate_id: hnd17nasr
    name: Salvador Nasralla
    name_variations:
      - Salvador Nasralla
      - Nasralla
    keywords:
      - Salvador Nasralla
    youtube_profile_url: https://www.youtube.com/@SalvaPresidente
    instagram_profile_url: https://www.instagram.com/salvadornasralla/
    twitter_profile_url: https://x.com/SalvaPresidente
    twitter_username: SalvaPresidente
    instagram_username: salvadornasralla
    youtube_username: '@SalvaPresidente'
    youtube_channel_id: UCjov_nNYqAUVPvyZDtMosRA
    youtube_uploads_playlist_id: UUjov_nNYqAUVPvyZDtMosRA

  - candidate_id: hnd18avil
    name: Jorge Nelson Ávila Gutiérrez
    name_variations:
      - Nelson Avila
    keywords:
      - Jorge Nelson Ávila Gutiérrez
    youtube_profile_url: null
    instagram_profile_url: https://www.instagram.com/nelsonavilapresidente
    twitter_profile_url: https://x.com/Nelson_Avila_Hn
    twitter_username: Nelson_Avila_Hn
    instagram_username: nelsonavilapresidente
    youtube_username: null
    youtube_channel_id: null
    youtube_uploads_playlist_id: null

  - candidate_id: hnd19rive
    name: Mario Rivera Callejas
    name_variations:
      - Mario Rivera Callejas
      - Mario Enrique Rivera Callejas
      - Chano Rivera
    keywords:
      - Mario Rivera Callejas
    youtube_profile_url: https://www.youtube.com/@soychanorivera
    instagram_profile_url: https://www.instagram.com/soychanorivera
    twitter_profile_url: https://x.com/SoyChanoRivera
    twitter_username: SoyChanoRivera
    instagram_username: soychanorivera
    youtube_username: '@soychanorivera'
    youtube_channel_id: UCo32FlwYfJA2g719PbprjJQ
    youtube_uploads_playlist_id: UUo32FlwYfJA2g719PbprjJQ

  - candidate_id: hnd20barr
    name: Ramon Barrios
    name_variations:
      - Ramon Barrios
    keywords:
      - Ramon Barrios
    youtube_profile_url: null
    instagram_profile_url: https://www.instagram.com/ramon.barrios05
    twitter_profile_url: https://x.com/ramonbarriosm
    twitter_username: ramonbarriosm
    instagram_username: ramon.barrios05
    youtube_username: null
    youtube_channel_id: null
    youtube_uploads_playlist_id: null
